# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Setup hobnob
description: Sets up Go and builds the hobnob bootstrap binary.

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Bootstrap hobnob
      shell: bash
      run: go build -o ./hobnob ./cmd/hobnob
